spanner_cdc: initial version
- Create new gcp_spanner_cdc input
- Add documentation with usage examples and field descriptions
- Implement changestreams package based on spanner-change-streams-tail [1]
- Port integration test [2] to connect test framework

The work is based on [1] which is ingested verbatim to the repo for rewrite.

The test passes, it requires true GCP Spanner to run as emulator does not implement CDC.

=== RUN   TestIntegrationSpannerInput
    integration_spanner_test.go:131: Created table "table_1745858793247275000" and stream "stream_1745858793247275000"
level=info msg="Sending inproc messages to ID: a73eca12-6a59-4df0-9a8d-e5a7b0aeb1ab" @service=benthos label="" path=root.output
level=info msg="Connecting to mock Spanner CDC stream: stream_1745858793247275000 (project: sandbox-rpcn, instance: rpcn-tests, database: changestreams)" @service=benthos label="" path=root.input
level=info msg="Input type gcp_spanner is now active" @service=benthos label="" path=root.input
level=error msg="Error reading from Spanner change stream: spanner: code = \"NotFound\", desc = \"Change Stream not found: stream_1745858793247275000\", requestID = \"1.de9c49fafffda880.2.1.6.1\"" @service=benthos label="" path=root.input
    integration_spanner_test.go:137: Dropped table "table_1745858793247275000" and stream "stream_1745858793247275000"
--- PASS: TestSpannerInput (24.15s)
PASS
ok      github.com/redpanda-data/connect/v4/internal/impl/gcp   25.028s

[1] https://github.com/cloudspannerecosystem/spanner-change-streams-tail/tree/main/changestreams
[2] https://github.com/lingio/go-common/blob/master/spanner/change_stream_test.go

Fixes CON-64